# Generated by Django 4.2.5 on 2024-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('edubackground', models.CharField(choices=[('1', 'Higher Secondary'), ('2', 'Diploma or Certificate Programs'), ('3', "Bachelor's Degree"), ('4', "Master's Degree"), ('5', 'Doctoral Degree (Ph.D.)')], default='1', max_length=30, null=True)),
                ('teachexp', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
